# Basic Configuration Example
# Copy this file to configs/config.yaml and update with your settings

azure_devops:
  organization_url: "https://dev.azure.com/your-organization"
  personal_access_token: "your-ado-pat-token"
  project: "your-project-name"
  
  query:
    work_item_types:
      - "Bug"
      - "User Story"
    states:
      - "New"
      - "Active"
      - "Done"

github:
  app_certificate_path: "./configs/adowi2gh.2025-10-13.private-key.pem"
  app_id: 123456
  installation_id: 987654
  owner: "your-github-organization"
  repository: "your-repository"

migration:
  batch_size: 25
  dry_run: false
  include_comments: true
  
  field_mapping:
    state_mapping:
      "New": "open"
      "Active": "open"
      "Done": "closed"
    
    type_mapping:
      "Bug": ["bug"]
      "User Story": ["enhancement"]
  
  user_mapping: {}

logging:
  level: "info"
  format: "text"
